### ISSUE TITLE
[BUG] onClick on a marker and popupOpen on its popup generates an error

### ISSUE THREAD

**Issue by bartocc** [miguelcobain/ember-leaflet#131]
See this twiddle

https://canary.ember-twiddle.com/7c5447061e1ba03d309a16b67410f90a?openFiles=templates.index.hbs%2C

If you click on a marker, you'll get the following error and no popup will appear.
`Cannot read property 'getPane' of null`. It looks like this._map is not set ...

If you click again on the marker, you should not get the error and see the popup.

Click on the other marker and the error appears again.

<img width="708" alt="capture d ecran 2017-02-07 a 11 01 30" src="https://cloud.githubusercontent.com/assets/47953/22686586/eb5e889c-ed24-11e6-8ad5-2fedca5fedf8.png">

**Comment by bartocc** [comment]
You might also get the following error in setOpacity

<img width="712" alt="capture d ecran 2017-02-07 a 11 03 19" src="https://cloud.githubusercontent.com/assets/47953/22686624/0da6d17a-ed25-11e6-9817-172444e7bbdc.png">

**Comment by formigarafa** [comment]
I saw stack trace similar to the first one with tooltips, by just hovering the layers.
That line in the top of the stack fails because it tries to call getPane on the tooltip._map property that is not set.
It does not happen every time, though.
When hovering fast, I believe when the mouse leaves the element the _map is nullified before the tooltip get rendered.

**Comment by formigarafa** [comment]
At #138 I fix the tooltip problem I commented above. I hope it helps with popup ones.

**Comment by bartocc** [comment]
Thx @formigarafa. When your PR will be merged and part of a new release, I'll test it against the twiddle.

**Comment by Techn1x** [comment]
I've come up against the same bug as well. I'm running ember-leaflet v3.0.11, and I get this error showing up (either the getPane is null or the setOpacity error) every single time I click a marker on my map.

My specific implementation is as follows;

template
```
{{#marker-layer location=asset.location onClick=(action 'selectAsset' asset) }}
    {{#popup-layer popupOpen=(readonly (eq asset.id selectedAsset.id)) }}
        {{asset.name}}
    {{/popup-layer}}
{{/marker-layer}}
```
controller
```
selectAsset: function(asset) {
    this.set('selectedAsset', asset);
},
```

I also have an external panel where you can click an item, and it calls (action 'selectAsset' asset) in the exact same way. Clicking items from the panel is completely fine and produces no errors, but clicking on the markers themselves generates an error every time.

I tried @formigarafa 's tooltip fix but in popup-layer.js for popups, and unfortunately it didn't seem to fix the issue (for me anyway)...

One workaround is to (obviously) remove the popupOpen=... binding from the popup-layer, but then when I click items in the panel the marker popups won't open (because now popupOpen isn't binded to the selected asset that has been chosen from the panel).

A better workaround that works for me is to remove onClick=... in the marker-layer and use onPopupopen=(action 'selectAsset' asset) instead. This seems to allow both the popup to appear from the marker being clicked on (a marker, by default, always opens its popup on click) as well as allow the popup to be binded and open from the external panel.

Panel asset item click -> asset selected -> popupOpen is set to true for the specific asset's marker
Marker click -> popup opens -> asset selected -> popupOpen is set to true again (meh)

I have a feeling the issue may be something to do with the timing of these two events happening when you click on a marker: marker onClick= causing the popup to open (via the popupOpen selectedAsset binding), at the same time as the marker trying to open it's popup (via the markers default action of opening it's popup).

Based on this theory, I *think* an alternative workaround could be to stop the marker from opening its popup as its default action when it is clicked, if there is a way to do this.

I hope this helps diagnose the issue or at least helps others get around it, because I spent a few hours on this one today, kind of frustrating really

Thanks

**Comment by bartocc** [comment]
I agree with @Techn1x. The bug is caused because **one** click on the marker generates **two** attempts to open the popup.

First, popupOpenDidChange on the PopupLayer component is called because the (eq) helper's value changed. This causes the popup layer to be added to the map's layers.

Then, the regular DOM click event fires and this causes a call to L.Map._openPopup. This method ends with

```js
if (this._map.hasLayer(this._popup) && this._popup._source === layer) {
  this.closePopup();
} else {
  this.openPopup(layer, e.latlng);
}
```

and since the popup layer has already been added to the map by popupOpenDidChange, `this._map.hasLayer(this._popup)` evaluates to true, which triggers `this.closePopup();` while the popup element is not yet in the DOM, finally ending with the `undefined/null is not an object` bug.

@miguelcobain, do you believe there is a way for ember-leaflet to handle this kind of situations ?

**Comment by bartocc** [comment]
To avoid the marker from opening its popup, you can create your own marker component and override its _openPopup method like this

```js
// app/components/marker-that-will-not-open-its-popup-on-click/component.js
import MarkerLayer from 'ember-leaflet/components/marker-layer';

export default MarkerLayer.extend({
  createLayer() {
    let layer = this._super(...arguments);
    layer._openPopup = () => {};
    return layer;
  }
});
```

**Comment by Techn1x** [comment]
Thanks for that, I'll test out overriding the _openPopup method in the marker and let you know how it goes.

I am hoping it may also fix this other issue I'm having, but not sure..
https://github.com/miguelcobain/ember-leaflet/issues/156

**Comment by Techn1x** [comment]
Finally got around to implementing the workaround that @bartocc mentioned, and it works quite well. This is a good enough solution for me, but perhaps may not be for others.

I imagine this is a pretty common scenario for an application to need two ways to open a popup (either via onClick of marker or via the popupOpen binding on the popup layer), so it would be nice if ember-leaflet had a way to handle when this occurs.

**Comment by Techn1x** [comment]
I don't seem to have this issue anymore, once updating to 3.1.2
