### ISSUE TITLE
geoJSON layer disappears on update

### ISSUE THREAD

**Issue by brancusi** [miguelcobain/ember-leaflet#147]
Hi,

Just ran into an issue during an upgrade from 
`ember 2.7 -> 2.8`
`ember-leaflet 3.0.2 -> 3.0.11`

When I pass a new geoJSON to a geoJSON layer, it no longer renders. The first time works fine, but second time doesn't work.

Here is a twiddle that demonstrates the issue: https://ember-twiddle.com/b38d89af79a19a30d59326851af22853?openFiles=controllers.application.js%2C

**Comment by brancusi** [comment]
Tracked the issue down to change from `3.0.9 -> 3.0.10`: https://github.com/miguelcobain/ember-leaflet/commit/f243c4063b811e47e3f79d2ff1d61007b0ff959e#diff-58985966d3dbfe85c245fb1aaaba3cfe

Also another twiddle showing it working on `3.0.9`: https://ember-twiddle.com/2b6a1b8a6145bbad8e03ce5ce3d03bb4?openFiles=twiddle.json%2C

**Comment by miguelcobain** [comment]
Thank you for the twiddle. I'll try to take a look today or tomorrow.

**Comment by brancusi** [comment]
Thank you

**Comment by miguelcobain** [comment]
@brancusi Using your twiddle, clicking the buttons seems to be updating the shape. What is the bug exactly?

**Comment by brancusi** [comment]
That's so weird. I had it the bug reproduced on two machines and mobile in that first twiddle. Now it's working correctly in 3.0.9.

Can you see if this twiddle shows the bug for you. I bumped leaflet to 3.0.10 and it's back: https://ember-twiddle.com/cdb7d81c108367b2c95ed33843c92cf6?openFiles=twiddle.json%2C

**Comment by brlodi** [comment]
I'm also seeing this issue on 3.0.10 but not 3.0.9. Thanks to @brancusi's callout of change https://github.com/miguelcobain/ember-leaflet/commit/f243c4063b811e47e3f79d2ff1d61007b0ff959e#diff-58985966d3dbfe85c245fb1aaaba3cfe I managed to narrow down the cause, and the problem is in line 33 of `geojson-layer.js`:
```js
this.pushDataToLeaflet(geoJSON.value);
```
As part of the change, the didUpdateAttrs() method is no longer pulling the new GeoJSON from the newAttrs object, but is getting the actual GeoJSON object off the layer component. Since a GeoJSON object doesn't have a `value` property, `pushDataToLeaflet` is getting called with `undefined` instead of valid GeoJSON.

The only necessary change is
```diff
- this.pushDataToLeaflet(geoJSON.value);
+ this.pushDataToLeaflet(geoJSON);
```
and it works again.

If you want me to submit a PR @miguelcobain I can, but that seems like a lot of overhead for such a small change.
