### ISSUE TITLE
icon helper has a too generic name

### ISSUE THREAD

**Issue by initram** [miguelcobain/ember-leaflet#175]
including ember-leaflet in my ember app broke part of my app that was not in anyway related to maps. The reason for this was that I has a property that was called "icon" that i wanted to use in a template.

My code looked like this:
`<span class={{icon}}></span>`

After adding ember-leaflet the class of the span became "[object Object]". This is due to the icon helper being used instead of my property. I really think you should call your helper `l-icon` or `leaflet-icon`, this would make it impossible to clash with properties as they can not contain dashes.

**Comment by miguelcobain** [comment]
Your code is invalid. A closing bracket is missing. I assume this isn't realted to the issue you mentioned. I didn't know helper lookup had priority over property lookup. Will investigate.

**Comment by initram** [comment]
I updated the code to include the end bracket, I must have missed it when I typed in the issue on github.

**Comment by kaermorchen** [comment]
I've caught a bug if use [ember-mdi](https://github.com/kaermorchen/ember-mdi) + ember-leaflet in one project.

ember-mdi have icon property inside [component](https://github.com/kaermorchen/ember-mdi/blob/master/addon/templates/components/mdi-icon.hbs).

Instead of 
`<use xlink:href="#account"></use>`
I get
`<use xlink:href="#[object Object]"></use>`

**Comment by miguelcobain** [comment]
@kaermorchen interesting. This is closely related with the lack of namespacing with addon provided helpers and this RFC https://github.com/emberjs/rfcs/pull/308

Ember prioritizes helpers, and then your `{{icon}}` will be resolved as a helper instead of property lookup.

A quick and dirty fix for your case would be if ember-mdi used `{{this.icon}}` instead of `{{icon}}` (maybe use the same approach for the other properties to avoid other possible conflicts).
This is something I can't really solve in ember-leaflet unless I introduce a breaking change (renaming the helper). :/

Namespacing everything with `{{l-something` might be what would solve all the conflicts. This is a sad situation.

**Comment by miguelcobain** [comment]
Will cross post my comment from https://github.com/Gavant/gavant-ember-button-basic/pull/3#issuecomment-403490843:

It really sucks that people need to do this in unrelated addons, but to solve this on ember-leaflet would mean introducing a breaking change (renaming the helper). Also, if I prefix the helper to leaflet-icon or something, it would probably mean that I would need to prefix all helpers. We never know what names people are using on their variables.

However, in my defense:

this is very easy to solve using {{this.property}} like in this PR, and with zero breaking changes for everyone
an Ember RFC was merged that basically deprecates {{property}} lookups, in favor of {{this.property}} lookups: emberjs/rfcs#308
module unification will also solve this because it will introduce namespacing for addons

For these reasons, I am closing this issue.
