### ISSUE TITLE
Highlight selected marker on map

### ISSUE THREAD

**Issue by kunerd** [miguelcobain/ember-leaflet#29]
In my application I have a route called 'places' that shows all places as markers on the map. I also managed to get the markers clickable. After clicking a marker the route changes to 'places/:place_id' and detailed information are shown next to the map. This works without any problems. Now, I'm trying to highlight the selected marker on the map, but I couldn't find a way to do this without using ArrayController and ItemController as I did some time ago. Also only one marker should be selectable at one time. 

I know that my question is more a general Ember question, sorry for that. But there aren't many resources on the internet on how to do these things without using the old controller class.

By the way: Thank you all for developing this nice ember-addon.

**Comment by miguelcobain** [comment]
> By the way: Thank you all for developing this nice ember-addon.

Thanks. My pleasure. :)

I think it is a good sign that the problems people are having with ember-leaflet are just "ember problems". Those kind of problems are more easily "googlable" and have the support of all the community and not just a single addon's creator/community.

So, if I understood correctly, you have a route for an individual place and a route for a collection of places. A quick solution for that is to access the individual route controller's model. Ember allows you to have dependencies within controllers, and this seems like a good case for that (please read https://guides.emberjs.com/v2.3.0/controllers/dependencies-between-controllers/).

So, I'll try to lay out an example:

```js
// your multiple places controller,
// where I assume your leaflet-map is being rendered
export default Ember.Controller.extend({
  placeController: Ember.inject.controller('place'),
  selectedPlace: Ember.computed.readOnly('placeController.model') //this is like a "read only alias"
});
```

```hbs
{{#leaflet-map lat=lat lng=lng}}

  {{#if selectedPlace}}
    {{!-- render a marker with a custom icon/popup here --}}
    {{marker-layer icon=highlightedIcon}}
  {{/if}}

  {{!-- I assume you have an each to render your places --}}
  {{#each model as |place|}}
    {{marker-layer ...}}
  {{/each}}

{{/leaflet-map}}
```

Then a problem arises. You're now probably rendering a place two times: one because it is a selected place and another because it is part of the places array.
Again, this is basically another ember problem.

You have at least two ways of solving that:

1. create a computed property that holds all the places *except* the selected one and then `{{#each` on that cp
2. use the addon `ember-truth-helpers` and test if the place is not the selected one inside the `{{#each`. Example:
```hbs
{{#each model as |place|}}
  {{#if (not-eq place selectedPlace)}}
    {{marker-layer ...}}
  {{/if}}
{{/each}}
```

If you have further questions, feel free to ask them. However, I'd strongly encourage you to meet other ember folks on Ember's slack. We have a great supportive community out there. :smile: 

Hope to meet you there.

**Comment by miguelcobain** [comment]
Ah, I think there is still another option which is to conditionally bind the icon:

```hbs
{{marker-layer icon=(if (eq place selectedPlace) highlightedIcon normalIcon)}}
```
