### ISSUE TITLE
Add support for interactive-icons

### ISSUE THREAD

**Issue by badazz91** [miguelcobain/ember-leaflet#33]
Right now marker-icons can only contain interactive elements inside of popups. It would be nice to have a marker-container that wraps for example a custom marker-icon in form of a ember-component. This would allow for realtime-icon-state-changes in an ember-way (think of places with state that can change over time).

After digging into the code this seems not possible right now, or did I oversee something?

**Comment by miguelcobain** [comment]
@badazz91 
You can have things like
```hbs
{{marker-layer location=location icon=selectedIcon}}
```

then your controller/component can change `selectedIcon` and the marker icon would change accordingly. `selectedIcon` would have to be an `L.icon` instance (a leaflet class).

Is that enough for your needs? If not, what API were you imagining for what you need?

**Comment by badazz91** [comment]
Think of an svg-icon-component with dynamic coloring, depending on state. The same thing you do for popup (hijacking L.popup), for markers (L.divIcon with ember-component embedded).

**Comment by miguelcobain** [comment]
I see.

In other words, why would
```hbs
{{#marker-layer location=location}}
  Popup content
{{/marker-layer}}
```
render into the popup and not the marker's icon?

We could do the same thing, but for icons (although just div icons, probably):
```hbs
{{#marker-layer location=location}}
  <div class="cutom-markup">
    <img src="my_custom_marker.png"/>
  </div>
{{/marker-layer}}
```

At the time it felt a natural way of easily creating popups.

As we know, ember components only provide two possible blocks: normal and the inverse.
So a possible API for this could be:

```hbs
{{#marker-layer location=location}}
  Popup content
{{else}}
  <div class="cutom-markup">
    <img src="my_custom_marker.png"/>
  </div>
{{/marker-layer}}
```

This is good because it is backwards compatible.
However, this has the major downside of not being able to define an icon **without** a popup.

So, another possible API for this could be
```hbs
{{#marker-layer location=location as |marker|}}

  {{#marker.popup-layer}}
    Popup content
  {{/marker.popup-layer}}

  {{#marker.icon-layer}}
    <div class="cutom-markup">
      <img src="my_custom_marker.png"/>
    </div>
  {{/marker.popup-layer}}

{{/marker-layer}}
```

Here, `marker.popup-layer` and `marker.icon-layer` are contextual components yielded by `marker-layer`. This would be a bit complex implementation, I think.

Another possibility would be to pass in the icon component as a contextual component:
```hbs
{{#marker-layer location=location icon=(component "my-custom-icon") as |marker|}}
  Popup content
{{/marker-layer}}
```

Would also be backwards compatible.
What are your thoughts on this?

/cc @ForSpareParts, maybe you having something to add to the discussion.

**Comment by fpauser** [comment]
Would also love to see support for custom markers - the 'complex' implementation looks good to me.

**Comment by badazz91** [comment]
The 'complex' would do the trick, I think.

**Comment by fpauser** [comment]
To illustrate it in more detail, with embedded components:

```handlebars
{{#each systems as |system|}}
  {{#marker-layer location=location as |marker|}}
    {{#marker.popup-layer}}
      {{system-info system=system}}
    {{/marker.popup-layer}}

    {{#marker.icon-layer}}
      {{system-marker color=(compute-state-color system.state)}}
    {{/marker.icon-layer}}
  {{/marker-layer}}
{{/each}}
```

**Comment by miguelcobain** [comment]
@fpauser you can achieve something similar today:

```js
auxSystem: computed('systems.@each.state', function() {
  let systems = this.get('systems');
  return systems.map(s => ({
    system: s,
    icon: this.makeIcon(s)
  }));
})
```

```hbs
{{#each auxSystem as |auxSystem|}}
  {{#marker-layer location=auxSystem.system.location icon=auxSystem.icon as |marker|}}
    {{system-info system=auxSystem.system}}
  {{/marker-layer}}
{{/each}}
```

The `makeIcon` function would return an appropriate leaflet icon given the system instance.

**Comment by fpauser** [comment]
Yes, this should work, will have a try. Thanks for pointing this out!

**Comment by ForSpareParts** [comment]
I've actually had to muck about with icons as well, so this is definitely interesting to me!

API-wise, I agree that defining the icons in the template would be nicer... and more complex. I guess `Icon` isn't even a `Layer` in Leaflet terms. It's just a... thing?

And, to make things even more fun: unlike popups, `DivIcon` doesn't take HTML elements, and doesn't have `setContent`/ `getContent`. You have to give it an HTML string when you create it. Which means that in order to get the template binding we'd have to create new `DivIcon`s every time the contents of the template changed.

In light of that, it seems like keeping icons as non-templatey things is the lesser evil. Maybe it's something to take up on the Leaflet side: could `DivIcon` expose a similar API to Popup? If that changed on Leaflet's end, I'd feel very good about contextual components as a solution.

**Comment by badazz91** [comment]
I have opened an issue in leaflet, concerning this API change for `L.divIcons`. Let's find out what those guys have to say about it.

Thanks for your thoughts!

**Comment by miguelcobain** [comment]
Here's the leaflet issue: https://github.com/Leaflet/Leaflet/issues/4259

**Comment by miguelcobain** [comment]
I've recently mentioned a helper for creating icons here: https://github.com/miguelcobain/ember-leaflet/issues/31#issuecomment-181875568

Could be the only option for now.

**Comment by miguelcobain** [comment]
Example:

```js
var myIcon = L.icon({
    iconUrl: 'my-icon.png',
    iconRetinaUrl: 'my-icon@2x.png',
    iconSize: [38, 95],
    iconAnchor: [22, 94],
    popupAnchor: [-3, -76],
    shadowUrl: 'my-icon-shadow.png',
    shadowRetinaUrl: 'my-icon-shadow@2x.png',
    shadowSize: [68, 95],
    shadowAnchor: [22, 94]
});
```
would turn into:
```hbs
{{marker-layer
  location=loc
  icon=(icon
    iconUrl="my-icon.png"
    iconRetinaUrl="my-icon@2x.png"
    iconSize=(point 38 95)
    iconAnchor=(point 22 94)
    popupAnchor=(point -3 -76)
    shadowUrl="my-icon-shadow.png"
    shadowRetinaUrl="my-icon-shadow@2x.png"
    shadowSize=(point 68 95)
    shadowAnchor=(point 22 94)
});
```

**Comment by brancusi** [comment]
This addon is really excellent. Thank you!

Looking forward to this addition.

**Comment by miguelcobain** [comment]
Update: https://github.com/miguelcobain/ember-leaflet/issues/31#issuecomment-194233809

**Comment by miguelcobain** [comment]
Added `point`, `icon`, and `div-icon` helpers in a published `2.2.0` version. :)
Changes: https://github.com/miguelcobain/ember-leaflet/commit/bc55707ddddd68cec978e4102a5cd7972cf14f56

Enjoy!

**Comment by miguelcobain** [comment]
Any suggestions for covering this on the docs?

**Comment by miguelcobain** [comment]
If all the icons use the same icon, you should either fallback to the old way or use

```hbs
{{#with (icon iconUrl="my-icon.png") as |myIcon|}}
  {{#each items as |item|}}
    {{#marker-layert icon=myIcon}}
      I'm {{item.name}}!
    {{/marker-layer}}
  {{/each}}
{{/with}}
```

**Comment by fpauser** [comment]
Added some basic documentation for the new helpers, see #43

**Comment by v3ss0n** [comment]
@miguelcobain  does this support SVG icons? 
Or should i render them to png first?

**Comment by miguelcobain** [comment]
@v3ss0n what is "this"?
I think there is no problem in using svgs. Worst case you create a divIcon where you place the SVG.

**Comment by v3ss0n** [comment]
By this , i wanted to mean `svg` instead of png
```
{{#with (icon iconUrl="my-icon.svg") as |myIcon|}} 
  {{#each items as |item|}}
    {{#marker-layer icon=myIcon}}
      I'm {{item.name}}!
    {{/marker-layer}}
  {{/each}}
{{/with}}
``

**Comment by v3ss0n** [comment]
Just to report that SVG works very well and Performance is as good as png, with dynamic sizes !!
