### ISSUE TITLE
Can't get subdomains to work with <layers.tile

### ISSUE THREAD

**Issue by ccoffey** [miguelcobain/ember-leaflet#428]
I've tried the following, which looks like it should work given [the docs](https://miguelcobain.github.io/ember-leaflet/docs/tile-layer):

```javascript
<LeafletMap @lat={{lat}} @lng={{lng}} @zoom={{zoom}} as |layers|>
  <layers.tile @url="http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}" @subdomains=['mt0','mt1','mt2','mt3'] />
</LeafletMap>
```

However I am seeing lots of errors on the console like: 

```
GET http://%27.google.com/vt/lyrs=m&x=9292&y=5844&z=14 net::ERR_NAME_NOT_RESOLVED
```

If I hard code a single subdomain it works:

```javascript
<LeafletMap @lat={{lat}} @lng={{lng}} @zoom={{zoom}} as |layers|>
  <layers.tile @url="http://mt3.google.com/vt/lyrs=m&x={x}&y={y}&z={z}" />
</LeafletMap>
```

So whats the correct way to pass subdomains?

**Comment by miguelcobain** [comment]
@ccoffey the problem is that `@subdomains=['mt0','mt1','mt2','mt3']` isn't valid handlebars syntax.

If you want to express arrays in ember, you should install [ember-array-helper](https://github.com/kellyselden/ember-array-helper) addon, and then use it like:

```hbs
<LeafletMap @lat={{lat}} @lng={{lng}} @zoom={{zoom}} as |layers|>
  <layers.tile
    @url="http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}"
    @subdomains={{array 'mt0' 'mt1' 'mt2' 'mt3'}}/>
</LeafletMap>
```

Let me know if this doesn't work for you and please reopen if that's the case. 👍

**Comment by ccoffey** [comment]
Thank you for your help @miguelcobain. I am clearly very new to Ember and I really appreciate you taking the time to help me. Thank you for your awesome project 🙇
