### ISSUE TITLE
Support for async relationship (Promise) for attributes

### ISSUE THREAD

**Issue by floqqi** [miguelcobain/ember-leaflet#5]
If I want to render a map using a relationship for attributes (lat/lng/zoom) the component fails with assertion error: `You must provide either valid bounds or a center (or lat/lng) and a zoom value.`

Example:

``` hbs
{{#leaflet-map lat=model.coordinate.lat lng=model.coordinate.lng zoom=model.coordinate.zoom}}
    {{tile-layer url='/api/tile/{z}/{x}/{y}'}}
{{/leaflet-map}}
```

Now I need to workaround with:

``` hbs
{{#if model.coordinate.isFulfilled}}
    {{!-- map --}}
{{/if}}
```

The `model` is loaded via the route and `model.coordinate` is loaded on-demand via ember-data (`belongsTo` relationship).

**Comment by miguelcobain** [comment]
@floqqi, what should the map do in this case? I'm not entirely sure of that.

I think this behavior is both expected and desired.
You can do things like:
```hbs
{{#if model.coordinate.isFulfilled}}
  {{!-- map --}}
{{else}}
  {{!-- loading spinner --}}
{{/if}}
```

This would make your UI more responsive. Alternatively make sure that `coordinate` is resolved at the route level, and deal with asynchrony with loading templates, for example.
Bottom line is that i don't see how a map can deal with this.

This could happen with marker locations as well. It would be more difficult there...

**Comment by floqqi** [comment]
My thought was that the map component should render a grey container (like http://www.ember-leaflet.com/docs/container) until `coordinate` is resolved.

Other libraries do those things as well. E. g. [ember-cli-materialize](https://github.com/mike-north/ember-cli-materialize) rerenders (specifically realigns labels) input elements after the passed value changed (promise is resolved).

**Comment by miguelcobain** [comment]
@floqqi I don't see anything at ember-cli-materialize that deals with promises.

My guess is that you see this behavior because it is the way our templates work.
If you write `{{model.someAsyncRelationship.name}}`, the template will update once the promise resolves.

That being said, we could make ember-leaflet promise aware, but it would need to be a global change.
Meaning that markers, tiles, and every other layer would need to support it.
Also, you just can't create some leaflet layers without some data. Example: you can't create a marker without a location. Solution: offload the creation of the marker until there is a valid location.

This could be possible, maybe improving around `leafletRequiredOptions` concatenated property.
I'm open to PRs/suggestions on this.

**Comment by badazz91** [comment]
I think, using  ```ember-promise-helpers``` could be an option, to improve promise handling.
---> https://github.com/fivetanley/ember-promise-helpers

It workes quite nice for us.

**Comment by Techn1x** [comment]
Having some promise-related issues with ember-leaflet, is this promise awareness for ember-leaflet still on the todo list or probably not going to happen for a while?

**Comment by miguelcobain** [comment]
This is a user concern. You must load your data properly and ember-leaflet shouldn't have to deal with that. For those reasons I'm closing this.
