### ISSUE TITLE
auto-center

### ISSUE THREAD

**Issue by maladon** [miguelcobain/ember-leaflet#57]
this stackoverflow shows how to auto-center a leaflet map based on the points being displayed.

https://stackoverflow.com/questions/10246157/leaflet-js-fit-geojson-co-ordinates-on-map-view

How do I do the same with ember-leaflet?

Thanks in advance!

**Comment by miguelcobain** [comment]
@maladon you can calculate the bounds of your geometries and passou it to leaflet-map like: `{{#leaflet-map bounds=bounds`.

I think there was a similar issue before.
I'll close this, but feel free to continue discussion if needed.

**Comment by owenek1** [comment]
I have a problem with bounds when there is only one element to display on the map it give me an error:
 
`Uncaught Error: Invalid LatLng object: (NaN, NaN)
    at L.LatLng (LatLng.js:24)
    at Object.unproject (Projection.SphericalMercator.js:29)
    at Object.pointToLatLng (CRS.js:31)
    at NewClass.unproject (Map.js:899)
    at NewClass._getBoundsCenterZoom (Map.js:250)
    at NewClass.fitBounds (Map.js:269)
    at Class.didCreateLayer (leaflet-map.js:59)
    at Class.didInsertParent (base-layer.js:90)
    at Object.applyStr [as default] (ember.debug.js:38924)
    at tryInvoke (ember.debug.js:39441)`

Also the same happens when there are two markers with the same location. When there are two different locations added to the bounds everything is correct. 

In the controller based on the results that I get, I create the bounds like this: 

`var latLngs = Ember.A();

    this.get('results').forEach(function(value){
      latLngs.push(value.get('location'));
    });

    this.set('bounds', L.latLngBounds(latLngs));`

Then in the template I have something like this: 

`{{#leaflet-map bounds=bounds class="fullscreen-map" as |layers|}}
        {{layers.tile url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
        {{#each results as |provider|}}
          {{#layers.marker location=provider.location as |marker|}}
            {{#marker.popup}}
              <h4>{{provider.businessName}}</h4>
              <dl>
                <dt>{{t 'sp-provider-map.address'}}</dt>
                <dd>{{provider.street}} {{provider.houseNumber}}, {{provider.postCode}} {{provider.city}}</dd>
                <dt>{{t 'sp-provider-map.rating'}}</dt>
                <dd class="rating">{{{sp-provider-rating rating=provider.rating}}}</dd>
              </dl>
            {{/marker.popup}}
          {{/layers.marker}}
        {{/each}}
      {{/leaflet-map}}`

Do you know what can be the problem ?
