### ISSUE TITLE
individual popup styles for  {{#marker-layer}}

### ISSUE THREAD

**Issue by OlmoDalco** [miguelcobain/ember-leaflet#58]
Hi, I am trying to define individual css styles for the popups of different maker-cluster-layers by adding classs to them. However I am not sure how to properly use the className Option on  {{#marker-layer}} and can't get it to work. Could you provide an example how to add classes to popups?

**Comment by miguelcobain** [comment]
@OlmoDalco You're right. It currently isn't possible. Right now popup content is obtained from the `marker-layer` component. Leaflet's popups have a `className` property, but we don't have access to it.
How do you imagine the API for this?

**Comment by IAmJulianAcosta** [comment]
@miguelcobain could you please give me a little explanation about where are popups created? I have this problem and will work to solve it

**Comment by IAmJulianAcosta** [comment]
@miguelcobain , I think that we could pass `className` property to `marker-layer`, something like:

```{{#marker-layer lat=lat lng=lng className="Foo"}}
	FooBar
{{/marker-layer}}```

I'm familiarizing with the library now, but looking how some parts are implemented, I could suggest something like:

`mixins/popup.js`
```
 popupOptions : computed (function () {
	let leafletOptions = this.get ('leafletPopupOptions');
	let options        = {};
	leafletOptions.forEach (optionName => {
		if (this.get (optionName) !== undefined) {
			options[optionName] = this.get (optionName);
		}
	});
	return options;
  }),
didCreateLayer() {
    this._super(...arguments);
    if (this.get('hasBlock')) {
      this._popup = this.L.popup(this.get ('popupOptions'), this._layer);
```

`components/marker-layer.js`
```
leafletPopupOptions: [
	'className'
],
```

We also could add all the [http://leafletjs.com/reference.html#popup](properties) from `L.popup` to `leafletPopupOptions, so the popup is configurable.

If you're ok with this I could create a PR

**Comment by miguelcobain** [comment]
@IAmJulianAcosta i don't agree with

```hbs
{{#marker-layer lat=lat lng=lng className="Foo"}}
  FooBar
{{/marker-layer}}
```

because one may think that is the className of the marker layer and not the popup.

Ember provides us the `hash` helper, so I would agree with an API that puts all the popup options in a hash like this:

```hbs
{{#marker-layer lat=lat lng=lng
  popupOptions=(hash
    className="foo-popup"
    offset=(point 0 0)
    zoomAnimation=false
  )}}
  FooBar
{{/marker-layer}}
```

This logic belongs to popup mixin, in this line: https://github.com/miguelcobain/ember-leaflet/blob/master/addon%2Fmixins%2Fpopup.js#L57

This is basically a one line change. :)

It would be great if you could PR this with the respective test, @IAmJulianAcosta / @OlmoDalco

**Comment by miguelcobain** [comment]
@IAmJulianAcosta i don't agree with

```hbs
{{#marker-layer lat=lat lng=lng className="Foo"}}
  FooBar
{{/marker-layer}}
```

because it looks like the `className` is being applied to the marker and not the popup.

Ember provides us the `hash` helper. I would love an API like this:

```hbs
{{#marker-layer lat=lat lng=lng
  popupOptions=(hash
    className="foo"
    offset=(point 10 10)
    zoomAnimation=false
  )}}
  FooBar
{{/marker-layer}}
```

We would just forward the `popupOptions` hash to the popup creation.
Good news is that **this is basically a one line change** to:
`this._popup = this.L.popup(this.get('popupOptions'), this._layer);`

It would be great if you could provide a PR with the respective tests for this. :)

**Comment by OlmoDalco** [comment]
Hi Miguel,
thanks a lot. The suggested one line change works perfectly!

**Comment by IAmJulianAcosta** [comment]
@miguelcobain do you know from when `hash` is available?

**Comment by miguelcobain** [comment]
@IAmJulianAcosta since ember 2.3 http://emberjs.com/blog/2016/01/15/ember-2-3-released.html#toc_hash-helper

But there is a hash helper polyfill to make it available into, until, ember 1.13: https://github.com/cibernox/ember-hash-helper-polyfill

**Comment by IAmJulianAcosta** [comment]
Should I add the polyfill as a dependency in the PR?

**Comment by miguelcobain** [comment]
@IAmJulianAcosta no, see my comment on the PR

**Comment by miguelcobain** [comment]
fixed by https://github.com/miguelcobain/ember-leaflet/pull/62

**Comment by IAmJulianAcosta** [comment]
@miguelcobain I'm having problems setting `offset` property in popup. The property is passed to `L.popup`. I printed value in `L.popup.initialize` and is the value I used in template, but when rendering in `_updatePosition`, the value is class default, `0, -7`.

Any idea about why?
