### ISSUE TITLE
[docs] links/version

### ISSUE THREAD

**Issue by sdahlbac** [miguelcobain/ember-leaflet#672]
Latest in the docs points to 4.1.0
api docs are in the form of `<LeafletMap/>`

In here there are a lot of broken links to e.g. `http://leafletjs.com/reference-1.0.2.html#geojson-style` (it probably should be `https://leafletjs.com/reference.html#geojson-filter`)

I thought I'd have a go at fixing those reference links, but when I run in master the api docs are in the form of `{{leaflet-map}}` and a lot less content.

Am I missing something here or is it now preferred to go back to mustache style invocation?

**Comment by miguelcobain** [comment]
First, version 5.0.0 should be the the default docs now. I'll see what's going on.

Second, yeah, the "curly" syntax is not recommended, but it's just something that happens when using ember-cli-addon-docs. 🤷‍♂️ 
Before version 5 I was not using ember-cli-addon-docs to generate that. In version 5 we're no longer pointing to leaflet docs. I just copied the text over to this project.

I'll keep this issue open to track why the lastest docs aren't the default (even though they are available at https://miguelcobain.github.io/ember-leaflet/versions/master/)

**Comment by miguelcobain** [comment]
So, the curly invocation form is an upstream issue being tracked here: https://github.com/ember-learn/ember-cli-addon-docs/issues/195

Regarding the ember-leaflet docs, they are now updated to `v5.0.0`.
Thanks for reporting!
