### ISSUE TITLE
Uncaught TypeError: Cannot read property 'meta' of null

### ISSUE THREAD

**Issue by fpauser** [miguelcobain/ember-leaflet#91]
See the screenshot below. It happens in the `tile-layer` component, and I have no clue how to fix this - seems related to https://github.com/emberjs/ember.js/issues/13494.

One thing to note: Initial rendering of the map works fine, but changing the route and coming back always results in this error - so maybe a problem with rendering in ember.

![ember-leaflet-meta-of-null](https://cloud.githubusercontent.com/assets/7302/17135849/1cfbf656-5332-11e6-9c6a-7627cf2925de.png)

**Comment by miguelcobain** [comment]
version of ember-leaflet?

**Comment by miguelcobain** [comment]
This is a known bug that happens on ember 2.6+.

**Comment by fpauser** [comment]
Using version 2.2.7 of ember-leaflet - thanks for your hint, so downgrading to ember-2.5.x is the only option?

**Comment by miguelcobain** [comment]
Unfortunately, yes. I'm working on a failing test so that this can be solved in core.

**Comment by miguelcobain** [comment]
@fpauser this was fixed in the release channel. 🎉 
There still wasn't a point release for this.
You can use `bower install --save ember#release` to use a version with this bugfix for now.
We should have a 2.7.2 ember version with this fix soon!

So, to recap, ember versions 2.6, 2.7.0 and 2.7.1 have this bug. Use anything else.
